# Test your FastAPI endpoints

###  Get root
GET http://127.0.0.1:8000/
Accept: application/json

###  Get exercises
GET http://127.0.0.1:8000/exercises
Accept: application/json

### Post full exercise
POST http://127.0.0.1:8000/exercises
Content-Type: application/json

{
  "name": "Exercise number {{$randomInt}}",
  "description": "Description: {{$randomCatchPhraseAdjective}} {{$randomCatchPhrase}}"
}

### Post exercise with no description
POST http://127.0.0.1:8000/exercises
Content-Type: application/json

{
  "name": "Exercise number {{$randomInt}}"
}

### Get a single exercise
GET http://127.0.0.1:8000/exercises/1

### Update an exercise
PUT http://127.0.0.1:8000/exercises/2
Content-Type: application/json

{
  "name": "Exercise number {{$randomInt}}",
  "description": "{{$randomCatchPhraseAdjective}} {{$randomCatchPhrase}}. {{$randomCatchPhrase}}."
}

### Delete an exercise
DELETE http://127.0.0.1:8000/exercises/1

> {%
client.test("Delete executed successfully", function() {
  client.assert(response.status === 204, "Response status is not 204");
});
%}